JAMAB_homepage:
 pattern:  /
 defaults: { _controller: AlimentosBundle:Default:index }

JAMAB_listar:
  pattern:  /listar
  defaults: { _controller: AlimentosBundle:Default:listar }

JAMAB_insertar:
  pattern:  /insertar
  defaults: { _controller: AlimentosBundle:Default:insertar }

JAMAB_buscar:
  pattern:  /buscar
  defaults: { _controller: AlimentosBundle:Default:buscarPorNombre }

JAMAB_ver:
  pattern:  /ver/{id}
  defaults: { _controller: AlimentosBundle:Default:ver }
